name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install packages
      run: ls && sudo apt install -y openscad
      
    - name: Install dependencies
      run: make lp

    - uses: actions/upload-artifact@v3
      with:
        name: stls
        path: stl
